---
title: "DBLP_Naumann data preparation"
author: "Mohsen"
date: "2018_12_04"
output: html_notebook
---

Read xml data and extract author names from it. Write names in the proper format.

```{r}
library(data.table)
data_name = 'dblp_naumann'
out_csv_nodes_path <- sprintf('../out/%s_node_list.csv', data_name)
out_csv_gold_path <- sprintf('../out/%s_gold_pairs.csv', data_name)
data_csv_train_path <- sprintf('../data/%s_input.csv', data_name)
data_names_path <- sprintf('../data/%s_names.rds', data_name)

# ====================== read dblp xml data and extract names before 2012 ======================
# library(xml2)
# names <- xml_text(xml_find_all(read_xml("D:/University/PHDResearch/Dataset/C4_PEOPLE MATCHING/10-DBLP_Naumann/Data ALL xml/dblp.xml", options = c('DTDLOAD')),"/dblp/article[year<2012]/author"))
# saveRDS(names, file = data_names_path)
names <- readRDS(data_names_path)

names <- iconv(names, "UTF-8", "ASCII//TRANSLIT") # unaccent
train <- data.table(id = seq(length(names)), name=names, resolved_id = "")
fwrite(train, data_csv_train_path)


length(unique(names)) # [1] 7751 --> 706028
```

Read Gold standards

```{r}

gold_data <- fread("../data/dblp_naumann/DBLP10k_groundtruth.csv")
gold_data <- gold_data[which(gold_data$sameentity == "t" & gold_data$samename == "f"), c("author1", "author2")]
author_name_1 <- iconv(gold_data$author1, "UTF-8", "ASCII//TRANSLIT") # unaccent
author_name_2 <- iconv(gold_data$author2, "UTF-8", "ASCII//TRANSLIT") # unaccent
author_name_1 <- gsub('[`\'\\{\\}]', '', tolower(author_name_1))
author_name_2 <- gsub('[`\'\\{\\}]', '', tolower(author_name_2))

gold_dt <- data.table(author_name_1, author_name_2)
fwrite(gold_dt, out_csv_gold_path, sep = "\t")
```

# Adding RefId to GoldStandard

Add RefV id to the gold standards after generation of "xxx_node_list.csv"

Please run above code. Afterward run extract_name_hin.Rmd notebook and then run following code.

```{r}
gold_dt <- fread(out_csv_gold_path, sep = "\t")
nodes_dt <- fread(out_csv_nodes_path, sep = "\t")
refs_dt <- nodes_dt[which(nodes_dt[, 3] == 'REF'), c(1,2)]
names(refs_dt) <- c('id', 'name')

gold_dt <- merge(gold_dt, refs_dt, by.x = "author_name_1", by.y = "name")
gold_dt <- merge(gold_dt, refs_dt, by.x = "author_name_2", by.y = "name")

gold_dt <- gold_dt[, c(3,4,1,2)]
names(gold_dt) <- c("author_id_1", "author_id_2", "author_name_1", "author_name_2")
fwrite(gold_dt, out_csv_gold_path, sep = "\t")

```

